### ISSUE TITLE
How to bump major version

### ISSUE THREAD

**Issue by santoshkowshikhr** [miguelfito/github-bump-and-tag-action#8]
Hi,

Looking for an option to bump the major version. How to achieve this? Is a commit message the only way?

**Comment by miguelfito** [comment]
Hi @santoshkowshikhr,

Yes, is the only way.

This action is based on `semantic-release`, and this uses [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) by default.

You can check for further information [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular)
